### ISSUE TITLE
Bad data in technology drop-down

### ISSUE THREAD

**Issue by kevinfarrugia** [HTTPArchive/cwv-tech-report#10]
Excuse me if this is already a known issue or outside the scope of this report, but I noticed a number of strange "technologies" towards the end of the list. 

![Screenshot from 2021-10-28 16-36-59](https://user-images.githubusercontent.com/8075326/139279912-559ad1c9-bbab-4a59-91f1-dbf4250a4e39.png)

**Comment by max-ostapenko** [comment]
Looks like the cases of overridden native methods that were fixed in WPT recently.
