### ISSUE TITLE
Investigate missing adoption of Hostinger

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/cwv-tech-report#24]
Hostinger exists as a supported technology in Wappalyzer, but we're not detecting any pages that use them.

Looking at the Wappalyzer source code, this technology seems to be using an unusual detection method (DNS):

https://github.com/wappalyzer/wappalyzer/blob/c4704aa76175a98d4212bcaa126ceb1473e51e8e/src/technologies/h.json#L888-L902

@pmeenan is that something that is supported by the WPT agent's driver code?

cc @ThierryA

**Comment by pmeenan** [comment]
I have most of the DNS logic implemented and hooked up but still not getting detections from Wappalyzer.  I filed an issue to hopefully figure out if I'm holding it wrong

**Comment by pmeenan** [comment]
Should be fixed with the next crawl.  Just merged.  [Here](https://webpagetest.httparchive.org/result/220726_60_1/) is a sample test. It uses Hostinger, Google mail and Amazon SES which are detected through DNS SOA, MX and TXT records.

```json
"_detected": {
  "Ecommerce": "Cart Functionality",
  "Programming languages": "PHP,Java",
  "UI frameworks": "Bootstrap 5",
  "PaaS": "Amazon Web Services",
  "JavaScript frameworks": "Vue.js 6995",
  "Analytics": "Pinterest Conversion Tag,Microsoft Clarity 0.6.36,Google Analytics,Google Ads Conversion Tracking,Facebook Pixel 2.9.66,Cloudflare Browser Insights",
  "RUM": "New Relic,Cloudflare Browser Insights",
  "JavaScript libraries": "core-js 3.6.5",
  "Reviews": "Trustpilot",
  "Advertising": "Microsoft Advertising",
  "Hosting": "Hostinger",
  "Webmail": "Google Workspace",
  "Email": "Google Workspace,Amazon SES",
  "Tag managers": "Google Tag Manager",
  "A\/B Testing": "Google Optimize",
  "CDN": "Google Hosted Libraries,Cloudflare",
  "Font scripts": "Google Font API"
},
"_detected_apps": {
  "Cart Functionality": "",
  "PHP": "",
  "Java": "",
  "Bootstrap": "5",
  "Amazon Web Services": "",
  "Vue.js": "6995",
  "Pinterest Conversion Tag": "",
  "New Relic": "",
  "core-js": "3.6.5",
  "Trustpilot": "",
  "Microsoft Clarity": "0.6.36",
  "Microsoft Advertising": "",
  "Hostinger": "",
  "Google Workspace": "",
  "Google Tag Manager": "",
  "Google Optimize": "",
  "Google Hosted Libraries": "",
  "Google Font API": "",
  "Google Analytics": "",
  "Google Ads Conversion Tracking": "",
  "Facebook Pixel": "2.9.66",
  "Cloudflare Browser Insights": "",
  "Cloudflare": "",
  "Amazon SES": ""
},
```

I also added the raw DNS for the origin to the har:

```json
"_origin_dns": {
    "cname": [
        "www.hostinger.com.cdn.cloudflare.net."
    ],
    "ns": [
        "any2.hostinger.com.",
        "any1.hostinger.com."
    ],
    "mx": [
        "1 aspmx.l.google.com.",
        "10 aspmx3.googlemail.com.",
        "10 aspmx2.googlemail.com.",
        "5 alt2.aspmx.l.google.com.",
        "5 alt1.aspmx.l.google.com."
    ],
    "txt": [
        "\"v=spf1 ip4:31.220.23.4 include:_spf.google.com include:amazonses.com include:_spf.hostedemail.com include:_spf.psm.knowbe4.com -all\"",
        "\"apple-domain-verification=IyFbOUpTx9DUOFwL\"",
        "\"mailru-verification: a8a9886e0072b036\"",
        "\"google-site-verification=4EfGmYRIEIPWA_ACJsA5zFGUzzY1pa8Du2tiHb8EKuI\"",
        "\"google-site-verification=MOjKs17dYrFXyEPndU4bK505my3D0dyC63-c5mvaNGU\"",
        "\"nordpass-domain-verification=6b627232b00e4e9ea70693c7994f2d50\""
    ],
    "soa": [
        "any1.hostinger.com. dns.hostinger.com. 2021102522 10800 3600 604800 3600"
    ]
},
```

Will leave this open until we can verify after the crawl but DNS-based detections should be working now.

**Comment by rviscomi** [comment]
Great, thanks!

**Comment by ton31337** [comment]
I'm working at Hostinger, a quick comment: you can distinguish if the site is hosted under Hostinger using HTTP headers:

`platform: hostinger` or `server: hcdn`.

**Comment by rviscomi** [comment]
Thanks @ton31337, once those changes land in Wappalyzer we should be able to automatically pick them up in our reporting.

To close out this thread, it looks like @pmeenan's change worked and we started seeing Hostinger data in the CWV Tech Report in August

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1120896/206236286-b97dfe58-8b1c-45f0-ab7c-ea61ba761fb0.png">

**Comment by rviscomi** [comment]
Yeah it's possible using BigQuery, for example the top 10 Hostinger sites with the slowest TTFB:

```sql
WITH pages AS (
  SELECT DISTINCT
    root_page
  FROM
    `httparchive.all.pages`,
    UNNEST(technologies) AS t
  WHERE
    date = '2023-02-01' AND
    t.technology = 'Hostinger'
),

crux AS (
  SELECT
    CONCAT(origin, '/') AS root_page,
    p75_ttfb
  FROM
    `chrome-ux-report.materialized.metrics_summary`
  WHERE
    date = '2023-02-01'
)


SELECT
  root_page,
  p75_ttfb
FROM
  pages
JOIN
  crux
USING
  (root_page)
ORDER BY
  p75_ttfb DESC
LIMIT
  10
```

Results:

root_page | p75_ttfb
-- | --
https://medpress.az/ | 42300
https://aljens.info/ | 29100
https://boletimdopaddock.com.br/ | 22400
https://pvst.com.br/ | 20900
https://www.travelnthrill.com/ | 20300
https://mejora2.online/ | 19200
https://www.delsolinmobiliaria.com.ar/ | 18600
https://nimt.in/ | 17900
https://duplaimagemgastro.com.br/ | 17600
https://surveyandoffers.com/ | 17200

I'd be really curious to hear if this leads you to identifying any actionable issues. Keep me posted!

**Comment by ton31337** [comment]
Thanks @rviscomi!
