### ISSUE TITLE
Suggestions for new report features

### ISSUE THREAD

**Issue by benmccann** [HTTPArchive/cwv-tech-report#32]
Hi, I maintain a somewhat popular web framework that's included in the reports. I'd like to use the data here to understand how we can have faster sites built with our framework and if there are features we need to add, evangelize, etc. And I'd also like to understand why some frameworks have higher CWVs and whether there's anything we can learn from what they're doing.

Some ideas that would be helpful:
- It would be incredibly helpful to have a list of origins or at least a random sampling of a few dozen each time I run the report. If I can see some actual sites it will give me a lot more insight as I can manually check a number of the things below for a small sample of sites.
- I'd love to see aggregate Lighthouse suggestions. E.g. what percentage of origins are given the feedback "serve images in next-gen formats", "defer offscreen images", "properly size images", "serve static assets with an efficient cache policy", etc.
- Things like number of images, number of DOM elements, number of cookies, website category might help understand things about the types of sites being built with a framework.

**Comment by rviscomi** [comment]
Thanks @benmccann, those are great suggestions. Would it be helpful if we got you that info in something like a custom report first? That way you can get answers to what you're looking for sooner and we can apply what worked best for you to the dashboard.

**Comment by benmccann** [comment]
Sure! That would be amazing

**Comment by rviscomi** [comment]
Cool. Want to set up a time to chat and work out the details? You can email me at rviscomi@google.com.

**Comment by rviscomi** [comment]
Here's the sample of 100 SvelteKit and Astro sites, including their origin-level CWV performance: https://docs.google.com/spreadsheets/d/1YjIEI-52dFkxczhKyih5-SI8CKssQwHUoGXTeFkfm5Y/edit?usp=sharing

**Comment by benmccann** [comment]
Thanks Rick!! I think I've found the main cause of SvelteKit slowness by looking at the slow sites from the spreadsheet, so no need to spend any more time on this. I'll investigate some more on my side and confirm.

**Comment by rviscomi** [comment]
Nice! Let us know if there's anything else you need.

FYI @sarahfossheim seems like sample URLs would be useful for the v2 dashboard.

**Comment by benmccann** [comment]
To share my findings, a huge portion of sites failing core web vitals are deployed in SPA mode. We already discourage single page apps in our docs, but I've sent a PR to further highlight the dangers (https://github.com/sveltejs/kit/pull/11637). I also opened an issue to discuss whether there could be anything we might be able to do in the framework to warn users (https://github.com/sveltejs/kit/issues/11639).

Getting a full list of all SvelteKit URLs that appear on cwvtech.report would be helpful to do some further investigations.

It might also be interesting to split SvelteKit on cwvtech.report into SvelteKit SSR and SvelteKit SPA. We can differentiate because the single page apps generally have <= 1 DOM element before client-side rendering kicks in as pictured below. I'm not sure if that's enough to report on. I could also look into generating a `meta` tag or something to show what mode it's operating in.

![Screenshot from 2024-01-15 18-00-57](https://github.com/HTTPArchive/cwv-tech-report/assets/322311/7910407c-73be-49d4-a2e2-7fb8e52994c0)

**Comment by benmccann** [comment]
Just checking in on this, do you think it'd be possible to split SvelteKit in the report into SvelteKit SSR and SvelteKit SPA?

**Comment by rviscomi** [comment]
Yeah that sounds doable from our side. A `meta` tag would definitely be a more idiomatic way to differentiate between modes, if possible. When available, you could let us know here or open a PR against the [Wappalyzer detections](https://github.com/HTTPArchive/wappalyzer/blob/db8cf0c3e8d843993786c22710f2f625dac659ef/src/technologies/s.json#L6934) directly to get it implemented.=

**Comment by benmccann** [comment]
Thanks. Will do! It'll probably have to wait a couple months so that we can make the change as part of a major version. For now, I've filed an issue against the 3.0 milestone so that we don't lose track of it: https://github.com/sveltejs/kit/issues/11724

**Comment by kevinfarrugia** [comment]
@benmccann I wrote a [query](https://docs.google.com/spreadsheets/d/1Bqs3VoqC5oo9CCp8CsUs1ojNKGZ_BP8xUasyyi3hlTg/edit?gid=0#gid=0) that compares the LCP of website's using various frontend frameworks for client-side and server-side rendering.

If we look at mobile, SvelteKit client-side rendering has 36% (from 585 origins) of website's with good LCP, compared to 64% (from 3,302 origins) when using server-side. Let me know your feedback. I would be happy to update the query if needed.

![Percentage of websites with Good LCP by client_server rendering](https://github.com/user-attachments/assets/9d2612b7-5552-43c8-8ff6-b58115638891)

_Note that the query considers a web page client-side rendered if 75% of the HTML is generated on the client side._

**Comment by benmccann** [comment]
That is awesome!! Thank you!

My only other request would be if we could get Astro in the chart as well

**Comment by kevinfarrugia** [comment]
Hi @benmccann . I have added Astro (and Next.js) to the chart. Just a heads up that the number of origins (266) using Astro and client-side rendering is very small—I think this is somewhat expected.

![Percentage of websites with Good LCP by client_server rendering](https://github.com/user-attachments/assets/72e773ef-8c9f-44ea-8f08-4aa110c0cd70)

**Comment by danielroe** [comment]
would love to see data for Nuxt as well if possible 🙏

**Comment by kevinfarrugia** [comment]
@danielroe I have updated it to include Nuxt.js. Note that you can add any technology that is tracked in [HTTPArchive/wappalyzer](https://github.com/HTTPArchive/wappalyzer/).

I also changed the query to check page-level CrUX data instead of origin-level. This gives a more meaningful value.

![Percentage of websites with Good LCP by client_server rendering (1)](https://github.com/user-attachments/assets/fa6c97ed-31da-47fe-9611-06e1926b0c55)

Feedback welcome.

**Comment by rviscomi** [comment]
We're moving repos. I created sub-issues to track the individual feature requests raised here, so this should be safe to close out now.

Any new bugs or FRs for the Tech Report can be filed at https://github.com/HTTPArchive/httparchive.org/issues
