### ISSUE TITLE
Technology Comparison Data table headings are incorrect

### ISSUE THREAD

**Issue by nedsbeds** [HTTPArchive/cwv-tech-report#33]
In the data table headings for technology comparison tab, the headers "Percent good CWV ('24)"
& "Percent good CWV ('23)" appear to be transposed
![image](https://github.com/HTTPArchive/cwv-tech-report/assets/4272375/fa2b4b9e-38ee-4ae4-8474-cd75c8df0d91)

For instance, the data shows an upwards trend for most technologies in the graph which is contrary to the data in the above table
![image](https://github.com/HTTPArchive/cwv-tech-report/assets/4272375/d757794f-6e2e-4332-a20f-15dce806dccd)
![image](https://github.com/HTTPArchive/cwv-tech-report/assets/4272375/ffe7b300-30a7-411f-9b73-5ee22fd6bb7e)

**Comment by rviscomi** [comment]
The dashboard actually supports two ways of measuring whether websites have good CWV:

- '23: the traditional way using LCP, CLS, and FID
- '24: the upcoming way using LCP, CLS, and INP

Next month when INP takes effect as a CWV metric, we'll simplify the dashboard to only show the '24 version and rename it back to "good CWV".

So these stats don't actually correspond to the same metric at different points in time, rather, different metrics at the same point in time.
